/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.Imp_Vendedor;
import Logica.LogAdmin;
import clases.Administrador;
import clases.Vendedor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author accel
 */
public class GUIAdministrador extends javax.swing.JFrame {
    LogAdmin Logadmin = new LogAdmin();
    Imp_Vendedor Imp_Vendedor = new Imp_Vendedor();
    ArrayList<Vendedor> ArrayCliente = new ArrayList<Vendedor>();
    public GUIAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistrarVendedor = new javax.swing.JButton();
        jTextUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordVendedor = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextSector = new javax.swing.JTextField();
        jTextNombreVendedor = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarVendedor.setText("Registrar Vendedor");
        jButtonRegistrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jLabel1.setText("User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));
        getContentPane().add(jPasswordVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel3.setText("Sector");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));
        getContentPane().add(jTextSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));
        getContentPane().add(jTextNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));
        getContentPane().add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, -1));

        jLabel6.setText("Cedula");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));
        getContentPane().add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarVendedorActionPerformed
        // TODO add your handling code here:
        ArrayList<Vendedor> ArrayTemp = new ArrayList<Vendedor>();
        ArrayList<Vendedor> ArrayTemp1 = new ArrayList<Vendedor>();
        ArrayTemp = Imp_Vendedor.ImportarVendedor();
        String user = this.jTextUser.getText();
        String password = this.jPasswordVendedor.getSelectedText();
        String sector = this.jTextSector.getText();
        String nombres = this.jTextNombreVendedor.getText();
        String apellidos = this.jTextApellido.getText();
        String cedula = this.jTextCedula.getText();                   
        ArrayTemp1 = Logadmin.AgregarVendedor(Logadmin.RegistrarVendedor(user, password, sector, nombres, apellidos, cedula), ArrayTemp);
        try {
            Imp_Vendedor.GuardaArchivoVendedor(ArrayTemp1);
        } catch (IOException ex) {
            Logger.getLogger(GUIAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButtonRegistrarVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordVendedor;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextNombreVendedor;
    private javax.swing.JTextField jTextSector;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables
}
