/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author accel
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelApellidos1 = new javax.swing.JLabel();
        jLabelCedula1 = new javax.swing.JLabel();
        jLabelPreguntaMetodoPago = new javax.swing.JLabel();
        jLabelCorreo1 = new javax.swing.JLabel();
        jLabelContraReg = new javax.swing.JLabel();
        jTextFieldNombreReg = new javax.swing.JTextField();
        jTextFieldApellidoReg = new javax.swing.JTextField();
        jTextFieldCedulaReg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerAnioReg = new javax.swing.JSpinner();
        jSpinnerDia1 = new javax.swing.JSpinner();
        jSpinnerMesReg1 = new javax.swing.JSpinner();
        jButtonCancelarReg = new javax.swing.JButton();
        jLabelCodigoReg = new javax.swing.JLabel();
        jRadioButtonVisa = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPasswordContraRepReg = new javax.swing.JPasswordField();
        jPasswordFieldCodigo = new javax.swing.JPasswordField();
        jLabelContraRepReg2 = new javax.swing.JLabel();
        jLabelTarjetaReg1 = new javax.swing.JLabel();
        jLabelAnioFechaVenReg = new javax.swing.JLabel();
        jPasswordFieldContraReg1 = new javax.swing.JPasswordField();
        jSpinnerAnioFecha = new javax.swing.JSpinner();
        jLabelFechaVenReg = new javax.swing.JLabel();
        jSpinnerDiaFecha = new javax.swing.JSpinner();
        jLabelMesFechaVenReg = new javax.swing.JLabel();
        jTextFieldCorreoReg = new javax.swing.JTextField();
        jLabelContraRepReg1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButtonRegistrarReg1 = new javax.swing.JButton();
        jPasswordFieldTarjeta1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 90));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFecha.setText("Fecha de nacimiento");
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, 20));

        jLabelNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre1.setText("Nombre");
        getContentPane().add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 30));

        jLabelApellidos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApellidos1.setText("Apellido");
        getContentPane().add(jLabelApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 30));

        jLabelCedula1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCedula1.setText("Cédula");
        getContentPane().add(jLabelCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 20));

        jLabelPreguntaMetodoPago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPreguntaMetodoPago.setText("Agregar Metodo de Pago ");
        getContentPane().add(jLabelPreguntaMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, 20));

        jLabelCorreo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCorreo1.setText("Correo electrónico");
        getContentPane().add(jLabelCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        jLabelContraReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContraReg.setText("Contraseña");
        getContentPane().add(jLabelContraReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, 20));

        jTextFieldNombreReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNombreReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 290, 30));

        jTextFieldApellidoReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldApellidoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 290, 30));

        jTextFieldCedulaReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldCedulaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 290, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Año");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Dia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));
        getContentPane().add(jSpinnerAnioReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 60, -1));
        getContentPane().add(jSpinnerDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 40, -1));
        getContentPane().add(jSpinnerMesReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 40, -1));

        jButtonCancelarReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelarReg.setText("Cancelar");
        jButtonCancelarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarRegActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, -1, -1));

        jLabelCodigoReg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCodigoReg.setText("Codigo (CVV)");
        getContentPane().add(jLabelCodigoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, -1, 20));

        jRadioButtonVisa.setText("Visa");
        jRadioButtonVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVisaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        jRadioButton3.setText("MasterCard");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jRadioButton4.setText("DinersClub");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        jPasswordContraRepReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jPasswordContraRepReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 180, -1));

        jPasswordFieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jPasswordFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 80, -1));

        jLabelContraRepReg2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContraRepReg2.setText("Repetir Contraseña");
        getContentPane().add(jLabelContraRepReg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, 20));

        jLabelTarjetaReg1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTarjetaReg1.setText("Numero de Tarjeta");
        getContentPane().add(jLabelTarjetaReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, 20));

        jLabelAnioFechaVenReg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAnioFechaVenReg.setText("Año");
        getContentPane().add(jLabelAnioFechaVenReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, 20));

        jPasswordFieldContraReg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jPasswordFieldContraReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 180, -1));
        getContentPane().add(jSpinnerAnioFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 70, -1));

        jLabelFechaVenReg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFechaVenReg.setText("Fecha de vencimiento");
        getContentPane().add(jLabelFechaVenReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, 20));
        getContentPane().add(jSpinnerDiaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 50, -1));

        jLabelMesFechaVenReg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMesFechaVenReg.setText("Mes");
        getContentPane().add(jLabelMesFechaVenReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, 20));

        jTextFieldCorreoReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldCorreoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 290, 30));

        jLabelContraRepReg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContraRepReg1.setText("Seleccionar Metodo de Pago");
        getContentPane().add(jLabelContraRepReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, 20));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jButtonRegistrarReg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonRegistrarReg1.setText("Registrar");
        getContentPane().add(jButtonRegistrarReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, -1));

        jPasswordFieldTarjeta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jPasswordFieldTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVisaActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonCancelarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarReg;
    private javax.swing.JButton jButtonRegistrarReg1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAnioFechaVenReg;
    private javax.swing.JLabel jLabelApellidos1;
    private javax.swing.JLabel jLabelCedula1;
    private javax.swing.JLabel jLabelCodigoReg;
    private javax.swing.JLabel jLabelContraReg;
    private javax.swing.JLabel jLabelContraRepReg1;
    private javax.swing.JLabel jLabelContraRepReg2;
    private javax.swing.JLabel jLabelCorreo1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaVenReg;
    private javax.swing.JLabel jLabelMesFechaVenReg;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelPreguntaMetodoPago;
    private javax.swing.JLabel jLabelTarjetaReg1;
    private javax.swing.JPasswordField jPasswordContraRepReg;
    private javax.swing.JPasswordField jPasswordFieldCodigo;
    private javax.swing.JPasswordField jPasswordFieldContraReg1;
    private javax.swing.JPasswordField jPasswordFieldTarjeta1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButtonVisa;
    private javax.swing.JSpinner jSpinnerAnioFecha;
    private javax.swing.JSpinner jSpinnerAnioReg;
    private javax.swing.JSpinner jSpinnerDia1;
    private javax.swing.JSpinner jSpinnerDiaFecha;
    private javax.swing.JSpinner jSpinnerMesReg1;
    private javax.swing.JTextField jTextFieldApellidoReg;
    private javax.swing.JTextField jTextFieldCedulaReg;
    private javax.swing.JTextField jTextFieldCorreoReg;
    private javax.swing.JTextField jTextFieldNombreReg;
    // End of variables declaration//GEN-END:variables
}
