/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Vender extends javax.swing.JFrame {

    /**
     * Creates new form Vender
     */
    public Vender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBoletos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBoletos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsumibles = new javax.swing.JTable();
        jLabelRealizarVenta = new javax.swing.JLabel();
        jLabelConsumibles = new javax.swing.JLabel();
        jButtonVenta = new javax.swing.JButton();
        jCheckBoxFactura = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombreFac1 = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldNombreFac = new javax.swing.JTextField();
        jLabelNombreFac2 = new javax.swing.JLabel();
        jTextFieldRucFac = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabelTotalIvaLlenar = new javax.swing.JLabel();
        jLabelTotalLlenar = new javax.swing.JLabel();
        jLabelTotalIvaFac = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelPeli1 = new javax.swing.JLabel();
        jComboBoxPeli = new javax.swing.JComboBox<>();
        jLabelPuesto1 = new javax.swing.JLabel();
        jComboBoxHorario = new javax.swing.JComboBox<>();
        jButtonAgregarConsumibles = new javax.swing.JButton();
        jLabelPuesto2 = new javax.swing.JLabel();
        jComboBoxPuesto1 = new javax.swing.JComboBox<>();
        jButtonAgregarBoletos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableConsumibles1 = new javax.swing.JTable();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1182, 532));
        setPreferredSize(new java.awt.Dimension(1138, 587));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBoletos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBoletos.setText("Boletos");
        getContentPane().add(jLabelBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jTableBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Boleto", "Ubicacion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBoletos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 290, 90));

        jTableConsumibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableConsumibles);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 80));

        jLabelRealizarVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRealizarVenta.setText("Realizar Venta");
        getContentPane().add(jLabelRealizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabelConsumibles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelConsumibles.setText("Consumibles");
        getContentPane().add(jLabelConsumibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jButtonVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVenta.setText("Venta");
        getContentPane().add(jButtonVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jCheckBoxFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxFactura.setText("Realizar Factura");
        getContentPane().add(jCheckBoxFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreFac1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombreFac1.setText("Nombre:");
        jPanel1.add(jLabelNombreFac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabelDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDireccion.setText("Direccion:");
        jPanel1.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTextFieldDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 450, -1));

        jTextFieldNombreFac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNombreFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreFacActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 450, -1));

        jLabelNombreFac2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombreFac2.setText("RUC:");
        jPanel1.add(jLabelNombreFac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jTextFieldRucFac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRucFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRucFacActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRucFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 450, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Facturar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 600, 170));

        jLabelTotalIvaLlenar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabelTotalIvaLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 80, 20));

        jLabelTotalLlenar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabelTotalLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 80, 20));

        jLabelTotalIvaFac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalIvaFac.setText("Total + IVA:");
        getContentPane().add(jLabelTotalIvaFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 20));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotal.setText("Total:");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 470, 440));

        jLabelPeli1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPeli1.setText("Pelicula");
        getContentPane().add(jLabelPeli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jComboBoxPeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeliActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 110, -1));

        jLabelPuesto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPuesto1.setText("Horario");
        getContentPane().add(jLabelPuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jComboBoxHorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jButtonAgregarConsumibles.setText("Agregar");
        jButtonAgregarConsumibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarConsumiblesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarConsumibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabelPuesto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPuesto2.setText("Puesto");
        getContentPane().add(jLabelPuesto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jComboBoxPuesto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxPuesto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuesto1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jButtonAgregarBoletos.setText("Agregar");
        getContentPane().add(jButtonAgregarBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jTableConsumibles1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableConsumibles1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 280, 90));

        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldNombreFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreFacActionPerformed

    private void jTextFieldRucFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRucFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRucFacActionPerformed

    private void jComboBoxPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeliActionPerformed

    private void jComboBoxHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHorarioActionPerformed

    private void jComboBoxPuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuesto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPuesto1ActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonAgregarConsumiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarConsumiblesActionPerformed
        // TODO add your handling code here:
        /*
        Chip ObjChip = new Chip();
        rowSel = jTable1.getSelectedRow();
        if (jTable1.getValueAt(rowSel,1).toString().equals("1"))
            this.jCheckBox1.setSelected(true);
        else
            this.jCheckBox1.setSelected(false);
        this.jTextNumero.setText(jTable1.getValueAt(rowSel,0).toString());
        this.jTextSaldo.setText(jTable1.getValueAt(rowSel,2).toString());
        this.jTextMegas.setText(jTable1.getValueAt(rowSel,3).toString());
        ObjChip = ArrayChips.get(rowSel); //obtener el objeto cliente
        this.jTextCedula.setText(ObjChip.cliente.getCedula());
        this.jTextNombres.setText(ObjChip.cliente.getNombres());
        this.jTextApellidos.setText(ObjChip.cliente.getApellidos());
        */
        
    }                                    

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
        /*
        Chip ObjChip = new Chip();
        if (rowSel == -1) {
        JOptionPane.showMessageDialog(null, "No ha seleccionado");
        else{
            if (this.jButtonMod.getText().equals("Grabar")){
                ObjChip.setNumero(this.jTextNumero.getText());
                ObjChip.setActivo(1);
                ObjChip.setSaldo(Integer.parseInt(this.jTextSaldo.getText()));
                ObjChip.setMegas(Integer.parseInt(this.jTextMegas.getText()));
                
                ObjChip.cliente.setCedula(this.jTextCedula.getText());
                ObjChip.cliente.setNombres(this.jTextNombres.getText());
                ObjChip.cliente.setApellidos(this.jTextApellidos.getText());
                
                ArrayChips.set(rowSel, ObjChip);
                this.jButtonLisActionPerformed(evt);
                
                this.jTextNumero.setEnabled(false);
                this.jTextSaldo.setEnabled(false);
                this.jTextMegas.setEnabled(false);
                this.jTextCedula.setEnabled(false);
                this.jTextNombres.setEnabled(false);
                this.jTextApellidos.setEnabled(false);
                
                this.jButtonNue.setEnabled(true);
                this.jButtonEli.setEnabled(true);
                this.jButtonLis.setEnabled(true);
                this.jButtonCan.setEnabled(false);
                this.jButtonMod.setText("Modificar");
            }
            else
            {
                this.jButtonMod.setText("Grabar");
                this.jTextNumero.setEnabled(true);
                this.jTextSaldo.setEnabled(true);
                this.jTextMegas.setEnabled(true);
                this.jTextCedula.setEnabled(true);
                this.jTextNombres.setEnabled(true);
                this.jTextApellidos.setEnabled(true);
                
                this.jButtonNue.setEnabled(false);
                
                this.jButtonEli.setEnabled(false);
                this.jButtonLis.setEnabled(false);
                this.jButtonCan.setEnabled(true);
            }        
        }
        */
        

    }//GEN-LAST:event_jButtonAgregarConsumiblesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAgregarBoletos;
    private javax.swing.JButton jButtonAgregarConsumibles;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonVenta;
    private javax.swing.JCheckBox jCheckBoxFactura;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JComboBox<String> jComboBoxPeli;
    private javax.swing.JComboBox<String> jComboBoxPuesto1;
    private javax.swing.JLabel jLabelBoletos;
    private javax.swing.JLabel jLabelConsumibles;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombreFac1;
    private javax.swing.JLabel jLabelNombreFac2;
    private javax.swing.JLabel jLabelPeli1;
    private javax.swing.JLabel jLabelPuesto1;
    private javax.swing.JLabel jLabelPuesto2;
    private javax.swing.JLabel jLabelRealizarVenta;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalIvaFac;
    private javax.swing.JLabel jLabelTotalIvaLlenar;
    private javax.swing.JLabel jLabelTotalLlenar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableBoletos;
    private javax.swing.JTable jTableConsumibles;
    private javax.swing.JTable jTableConsumibles1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombreFac;
    private javax.swing.JTextField jTextFieldRucFac;
    // End of variables declaration//GEN-END:variables
}
